unbind C-b
set -g prefix C-a
bind C-a send-prefix
bind -r M-Up    resize-pane -U 5
bind -r M-Down  resize-pane -D 5
bind -r M-Left  resize-pane -L 5
bind -r M-Right resize-pane -R 5

# Status bar: black background, white text; subtle time on the right.
set -ga terminal-overrides ",*256col*:Tc"
set -g escape-time 10
set -g default-terminal "screen-256color"

set -g status-style "bg=black,fg=white"
set -g status-left-length 0
set -g mouse on
set -g status-right-length 50
set -g status-right "#[bg=colour240,fg=black] %H:%M:%S #[default]"
